services:
  mangawebasp:
    image: mangawebasp
    build:
      context: .
      dockerfile: MangaWebASP/Dockerfile

  mangaservice:
    image: mangaservice
    build:
      context: .
      dockerfile: MangaService/Dockerfile
  banner:
    image: banner
    build:
      context: .
      dockerfile: Banner/Dockerfile

  banners:
    image: banners
    build:
      context: .
      dockerfile: Banners/Dockerfile

  notification:
    image: notification
    build:
      context: .
      dockerfile: Notification/Dockerfile

  notificationmanageaccount:
    image: notificationmanageaccount
    build:
      context: .
      dockerfile: notificationManageAccount/Dockerfile
  chapterservice:
    image: chapterservice
    build:
      context: .
      dockerfile: ChapterService/Dockerfile


  account:
    image: account
    build:
      context: .
      dockerfile: Account/Dockerfile

  account-1:
    image: account-1
    build:
      context: .
      dockerfile: Account/Dockerfile

  workerservice1:
    image: workerservice1
    build:
      context: .
      dockerfile: WorkerService1/Dockerfile

  category:
    image: category
    build:
      context: .
      dockerfile: Category/Dockerfile

  categoryservice:
    image: categoryservice
    build:
      context: .
      dockerfile: CategoryService/Dockerfile

  categorydetailservice:
    image: categorydetailservice
    build:
      context: .
      dockerfile: CategoryDetailService/Dockerfile

  categorydetailsservice:
    image: categorydetailsservice
    build:
      context: .
      dockerfile: CategoryDetailsService/Dockerfile
