services:
  mangaservice:
    image: nqk090203/mangaservice:dev
    build:
      context: .
      dockerfile: MangaService/Dockerfile
    ports:
      - "0.0.0.0:5001:8080"

  notification:
    image: nqk090203/notification:dev
    build:
      context: .
      dockerfile: Notification/Dockerfile
    ports:
      - "0.0.0.0:5002:8080"

  chapterservice:
    image: nqk090203/chapterservice:dev
    build:
      context: .
      dockerfile: ChapterService/Dockerfile
    ports:
      - "0.0.0.0:5003:8080"

  account:
    image: nqk090203/account:dev
    build:
      context: .
      dockerfile: Account/Dockerfile
    ports:
      - "0.0.0.0:5004:8080"

  categoryservice:
    image: nqk090203/categoryservice:dev
    build:
      context: .
      dockerfile: CategoryService/Dockerfile
    ports:
      - "0.0.0.0:5005:8080"

  categorydetailsservice:
    image: nqk090203/categorydetailsservice:dev
    build:
      context: .
      dockerfile: CategoryDetailsService/Dockerfile
    ports:
      - "0.0.0.0:5006:8080"

  mangafavoriteservice:
    image: nqk090203/mangafavoriteservice:dev
    build:
      context: .
      dockerfile: MangaFavoriteService/Dockerfile
    ports:
      - "0.0.0.0:5007:8080"

  mangahistoryservice:
    image: nqk090203/mangahistoryservice:dev
    build:
      context: .
      dockerfile: MangaHistoryService/Dockerfile
    ports:
      - "0.0.0.0:5008:8080"

  notificationmangaaccount:
    image: nqk090203/notificationmangaaccount:dev
    build:
      context: .
      dockerfile: notificationMangaAccount/Dockerfile
    ports:
      - "0.0.0.0:5010:8080"

  infoaccount:
    image: nqk090203/infoaccount:dev
    build:
      context: .
      dockerfile: infoAccount/Dockerfile
    ports:
      - "0.0.0.0:5011:8080"

  mangaviewhistoryservice:
    image: nqk090203/mangaviewhistoryservice:dev
    build:
      context: .
      dockerfile: MangaViewHistoryService/Dockerfile
    ports:
      - "0.0.0.0:5012:8080"
  
  comment:
    image: nqk090203/comment:dev
    build:
      context: .
      dockerfile: Comment/Dockerfile
    ports:
      - "0.0.0.0:5013:8080"
  
  frontend.client:
    image: nqk090203/frontend.client:latest
    build:
      context: .
      dockerfile: FrontEnd/Dockerfile
    ports:
      - "0.0.0.0:4200:80"

networks:
  default:
    driver: bridge