services:
  mangaservice:
    image: mangaservice
    build:
      context: .
      dockerfile: MangaService/Dockerfile

  notification:
    image: notification
    build:
      context: .
      dockerfile: Notification/Dockerfile

  chapterservice:
    image: chapterservice
    build:
      context: .
      dockerfile: ChapterService/Dockerfile

  account:
    image: account
    build:
      context: .
      dockerfile: Account/Dockerfile


  categoryservice:
    image: categoryservice
    build:
      context: .
      dockerfile: CategoryService/Dockerfile


  categorydetailsservice:
    image: categorydetailsservice
    build:
      context: .
      dockerfile: CategoryDetailsService/Dockerfile

  mangafavoriteservice:
    image: mangafavoriteservice
    build:
      context: .
      dockerfile: MangaFavoriteService/Dockerfile

  mangahistoryservice:
    image: mangahistoryservice
    build:
      context: .
      dockerfile: MangaHistoryService/Dockerfile

  infonotificationaccount:
    image: infonotificationaccount
    build:
      context: .
      dockerfile: infoNotificationAccount/Dockerfile

  notificationmangaaccount:
    image: notificationmangaaccount
    build:
      context: .
      dockerfile: notificationMangaAccount/Dockerfile

  infoaccount:
    image: infoaccount
    build:
      context: .
      dockerfile: infoAccount/Dockerfile

  mangaviewhistoryservice:
    image: mangaviewhistoryservice
    build:
      context: .
      dockerfile: MangaViewHistoryService/Dockerfile
