services:
  mangaservice:
    image: mangaservice
    build:
      context: .
      dockerfile: MangaService/Dockerfile
    ports:
      - "0.0.0.0:5001:8080"

  notification:
    image: notification
    build:
      context: .
      dockerfile: Notification/Dockerfile
    ports:
      - "0.0.0.0:5002:8080"

  chapterservice:
    image: chapterservice
    build:
      context: .
      dockerfile: ChapterService/Dockerfile
    ports:
      - "0.0.0.0:5003:8080"

  account:
    image: account
    build:
      context: .
      dockerfile: Account/Dockerfile
    ports:
      - "0.0.0.0:5004:8080"

  categoryservice:
    image: categoryservice
    build:
      context: .
      dockerfile: CategoryService/Dockerfile
    ports:
      - "0.0.0.0:5005:8080"

  categorydetailsservice:
    image: categorydetailsservice
    build:
      context: .
      dockerfile: CategoryDetailsService/Dockerfile
    ports:
      - "0.0.0.0:5006:8080"

  mangafavoriteservice:
    image: mangafavoriteservice
    build:
      context: .
      dockerfile: MangaFavoriteService/Dockerfile
    ports:
      - "0.0.0.0:5007:8080"

  mangahistoryservice:
    image: mangahistoryservice
    build:
      context: .
      dockerfile: MangaHistoryService/Dockerfile
    ports:
      - "0.0.0.0:5008:8080"

  notificationmangaaccount:
    image: notificationmangaaccount
    build:
      context: .
      dockerfile: notificationMangaAccount/Dockerfile
    ports:
      - "0.0.0.0:5010:8080"

  infoaccount:
    image: infoaccount
    build:
      context: .
      dockerfile: infoAccount/Dockerfile
    ports:
      - "0.0.0.0:5011:8080"

  mangaviewhistoryservice:
    image: mangaviewhistoryservice
    build:
      context: .
      dockerfile: MangaViewHistoryService/Dockerfile
    ports:
      - "0.0.0.0:5012:8080"
  
  comment:
    image: comment
    build:
      context: .
      dockerfile: Comment/Dockerfile
    ports:
      - "0.0.0.0:5013:8080"
  
  frontend.client:
    image: frontend.client
    build:
      context: .
      dockerfile: FrontEnd/Dockerfile
    ports:
      - "0.0.0.0:4200:80"

networks:
  default:
    driver: bridge